In [1]:
import numpy as np

# create arrays
data1= [1, 2, 3, 4, 5, 6]  # list
arr1= np.array(data1)
print(arr1)
data2=[range(1, 5), range(5, 9)]
arr2= np.array(data2)
arr2.tolist() # convert array back to list


[1 2 3 4 5 6]


[[1, 2, 3, 4], [5, 6, 7, 8]]

In [85]:
# create special arrays
print("np.zeros(10) : ", np.zeros(10))
print("np.zeros((3, 6)): ", np.zeros((3, 6)))
print("np.ones(10): ", np.ones(10))
print("np.linspace (0, 1, 5): ", np.linspace(0, 1, 5)) # 0 to 1 with 5 points
print("np.logspace(0, 3, 4): ", np.logspace(0, 3, 4)) # 10^0 to 10^3 with 4 points
print("nu.full(10, 5.0): ", np.full(10, 5.0))

np.zeros(10) :  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
np.zeros((3, 6)):  [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
np.ones(10):  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
np.linspace (0, 1, 5):  [0.   0.25 0.5  0.75 1.  ]
np.logspace(0, 3, 4):  [   1.   10.  100. 1000.]
nu.full(10, 5.0):  [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [3]:
# arange is like range, except it returns an array( not a list)
int_array= np.arange(5)
float_array=int_array.astype(float)
int_array, float_array

(array([0, 1, 2, 3, 4]), array([0., 1., 2., 3., 4.]))

In [4]:
# Examining arrays 
arr1.dtype  # dtype(('int32'))
arr2.dtype  # dtype(('int32'))
arr2.ndim  # 2
arr2.shape  # (2, 4)
arr2.size   # 8
len(arr2)   #2 the number of lignes 

2

In [5]:
# Reshaping 
arr= np.arange(10, dtype=float).reshape((2, 5))
print(arr.shape)
print(arr.reshape(5, 2))

(2, 5)
[[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]
 [8. 9.]]


In [6]:
# add an axis
a=np.array([0, 1])
a_col= a[: , np.newaxis]
print(a_col)

[[0]
 [1]]


In [7]:
# transpose
a_col.T

array([[0, 1]])

In [8]:
# Flatten: always returns a flat copy of the original array
arr=np.arange(10, dtype=float).reshape((2, 5))
arr_flat= arr.flatten()
arr_flat[0]=33

print(arr_flat)
print(arr)

[33.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]


In [9]:
# ravel: returns a view of original array whenever possible 
arr_ravel= arr.ravel()
arr_ravel[0]=33
print(arr_ravel)
print(arr)

[33.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
[[33.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]]


In [10]:
x=np.arange(2*3*4)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [11]:
x=x.reshape(2, 3, 4)
print(x)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [12]:
# selection get first plan
print(x[0, :, :])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [13]:
# selection get first rows
print(x[:,0,:])

[[ 0  1  2  3]
 [12 13 14 15]]


In [14]:
# selection get first columns
print(x[:,:,0])

[[ 0  4  8]
 [12 16 20]]


In [15]:
# Stack arrays

a= np.array([0, 1])
b=np.array([2, 3])
ab= np.stack((a, b)).T

# or 
ab_hstack=np.hstack((a[:, None], b[:, None]))
print(ab)
print(ab_hstack)


[[0 2]
 [1 3]]
[[0 2]
 [1 3]]


In [16]:
# Selection 
arr= np.arange(10, dtype=float).reshape((2, 5))
print(arr[0][1])
print(arr)

1.0
[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]


In [17]:
#slicing 
print(arr[0, :])
print(arr[: , 0])
print(arr[:, :2])
print(arr[:, 2:])
arr2= arr[:, 1:4]
print(arr2)

[0. 1. 2. 3. 4.]
[0. 5.]
[[0. 1.]
 [5. 6.]]
[[2. 3. 4.]
 [7. 8. 9.]]
[[1. 2. 3.]
 [6. 7. 8.]]


In [18]:
# Row 0 reverse order
print(arr[:, ::-1])

[[4. 3. 2. 1. 0.]
 [9. 8. 7. 6. 5.]]


In [19]:
# fancy indexing: Integer or boolean array indexing 
arr2=arr[:, [1, 2, 3]]
print(arr2)
arr2[0, 0]=44
print(arr2)
print(arr)

[[1. 2. 3.]
 [6. 7. 8.]]
[[44.  2.  3.]
 [ 6.  7.  8.]]
[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]


In [20]:
# boolean arrays indexing
arr2= arr[arr>5]
print(arr2)
arr2[0]=55
print(arr2)

[6. 7. 8. 9.]
[55.  7.  8.  9.]


In [21]:
arr[arr>5]=0
print(arr)

[[0. 1. 2. 3. 4.]
 [5. 0. 0. 0. 0.]]


In [22]:
# boolean arrays indexing continues
names=np.array(['bob', 'joe', 'will', 'bob'])

print(names=='bob')
print(names[names!='bob'])
print((names=='bob')| (names=='will'))
names[names!='bob']='joe'
print(names)
print(np.unique(names))

[ True False False  True]
['joe' 'will']
[ True False  True  True]
['bob' 'joe' 'joe' 'bob']
['bob' 'joe']


In [23]:
# vectorized operations 
nums=np.arange(10)
print(nums*10)
nums=np.sqrt(nums) 
print(nums)
print(np.ceil(nums)) # also floor round to nearest int
print(np.isnan(nums)) # check for NAN

print(nums+np.arange(10))
print(np.maximum(nums, np.array([1, -2, 3, -4, 5, 1, -2, 3, -4, 5])))

[ 0 10 20 30 40 50 60 70 80 90]
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
[0. 1. 2. 2. 2. 3. 3. 3. 3. 3.]
[False False False False False False False False False False]
[ 0.          2.          3.41421356  4.73205081  6.          7.23606798
  8.44948974  9.64575131 10.82842712 12.        ]
[1.         1.         3.         1.73205081 5.         2.23606798
 2.44948974 3.         2.82842712 5.        ]


In [24]:
# compute euclidien distance between 2 vectors 
vect1= np.random.randn(10)
vect2= np.random.randn(10)
dist= np.sqrt(np.sum((vect1-vect2)**2))
print(dist)

4.197269114431608


In [25]:
# math and stats 
rnd= np.random.randn(4, 2)
print(rnd)
print(rnd.mean())
print(rnd.std())
print(rnd.argmax())# index of maximum element 
print(rnd.sum())
print(rnd.sum(axis=0)) # sum of columns
print(rnd.sum(axis=1)) # sum of rows


[[-2.16329024  0.13537444]
 [ 1.00189912 -0.13356836]
 [-0.13605882 -0.97089078]
 [ 0.4029613  -1.28912973]]
-0.3940878836719277
0.9528067330445732
2
-3.1527030693754217
[-0.89448864 -2.25821443]
[-2.02791581  0.86833077 -1.1069496  -0.88616843]


In [30]:
# methods for boolean arrays
print(rnd)
print((rnd> 0).sum()) # count the number of positif values
print((rnd>0).any()) # checks if any value is true 
print((rnd>0).all()) # checks if all values are true

[[-2.16329024  0.13537444]
 [ 1.00189912 -0.13356836]
 [-0.13605882 -0.97089078]
 [ 0.4029613  -1.28912973]]
3
True
False


In [35]:
# random numbers
np.random.seed(1234) # set the seed
print(np.random.rand(2, 3)) # (2, 3) matrix in [0, 1]
print(np.random.randn(10)) # random normal (mean 0 sd 1)
print(np.random.randint(0, 3, 10)) # 10 randomly picked 0 or 1 or 2

[[0.19151945 0.62210877 0.43772774]
 [0.78535858 0.77997581 0.27259261]]
[ 8.59588414e-01 -6.36523504e-01  1.56963721e-02 -2.24268495e+00
  1.15003572e+00  9.91946022e-01  9.53324128e-01 -2.02125482e+00
 -3.34077366e-01  2.11836468e-03]
[2 2 2 0 1 0 2 0 1 2]


In [48]:
a=np.random.randint(5, size=(4, 3))
b= np.random.randint(3, size=(1,3))
print("%s + %s = %s"%(a, b, a+b))

[[2 1 0]
 [0 4 4]
 [0 0 1]
 [3 1 4]] + [[1 2 1]] = [[3 3 1]
 [1 6 5]
 [1 2 2]
 [4 3 5]]


In [86]:
np.random.seed(12)
x=np.random.rand(4,2)
x, x.shape , x[0,0]
        

(array([[0.15416284, 0.7400497 ],
        [0.26331502, 0.53373939],
        [0.01457496, 0.91874701],
        [0.90071485, 0.03342143]]),
 (4, 2),
 0.15416284237967237)

In [83]:
def row_max(x):
    dct={}
    max=0
    for i in range(x.shape[1]):
        for j in range(x.shape[0]):
            if max < x[j,i]:
                max=x[j,i]
                ii=i
                jj=j
        dct[str(jj),str(ii)]= max
    return dct
row_max(x)

{('3', '0'): 0.9007148541170122, ('2', '1'): 0.918747008099885}

In [87]:
%timeit np.sum(x)

6.93 µs ± 268 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [90]:
# argsort renvoie un array avec les indices des données initiales triée 
arr= np.array([3, 1, 2])
print(np.argsort(arr))

[1 2 0]


In [96]:
# avg = sum(a * weights) / sum(weights)
arr= np.arange(6).reshape((3, 2))
print(arr)
print(np.average(arr, axis=1, weights=[1.4, 1.2]))

[[0 1]
 [2 3]
 [4 5]]
[0.46153846 2.46153846 4.46153846]
